language: python
python:
  - "3.12"

dist: jammy

install:
  - pip install -r requirements-dev.txt

before_script:
  - python manage.py migrate --noinput

script:
  - python -m black --check .
  - python -m flake8 .
  - coverage run manage.py test

after_success:
  - coveralls --service=github

deploy:
  provider: elasticbeanstalk
  edge: true
  access_key_id: $AWS_ACCESS_KEY_ID
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  region: us-east-1
  app: swe1-polls-app
  env: swe1-polls-prod
  bucket: swe1-polls-app
  on:
    branch: main